#TODO TO MOVE TO ROOT!
[versions]
koin = "3.5.3-wasm-1"
kotlin = "1.9.20"
stately = "2.0.5"
junit = "4.13.2"
mockito = "4.7.0"
coroutines = "1.8.0-RC2" #1.7.3 as last stable

[libraries]
extras-stately = { module = "co.touchlab:stately-concurrency", version.ref = "stately"}
test-junit = {module = "junit:junit", version.ref = "junit"}
test-mockito = {module = "org.mockito:mockito-inline", version.ref = "mockito"}
test-coroutines = {module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines"}

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
