name: Test Examples

on:
  pull_request:

concurrency:
  group: test-examples-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install
        run: cd projects && ./install.sh

      - name: Test Examples
        run: cd examples && ./test.sh

